/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package topgearshop.views;

import java.awt.event.ActionListener;

/**
 *
 * @author rmattaway
 */
public class TopGearMainUI extends javax.swing.JFrame {

  /**
   * Creates new form TopGearMainUI
   */
  public TopGearMainUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    activityView1 = new topgearshop.views.ActivityView();
    jLabel1 = new javax.swing.JLabel();
    lblWorkOrders = new javax.swing.JLabel();
    lblCustomers = new javax.swing.JLabel();
    lblVehicles = new javax.swing.JLabel();
    lblInventory = new javax.swing.JLabel();
    lblReports = new javax.swing.JLabel();
    lblUsers = new javax.swing.JLabel();
    lblServiceItems = new javax.swing.JLabel();
    lblWarranty = new javax.swing.JLabel();
    pnlCustomers = new javax.swing.JPanel();
    cmdCreateCustomer = new javax.swing.JButton();
    cmdEditCustomer = new javax.swing.JButton();
    cmdFindCustomer = new javax.swing.JButton();
    pnlWorkOrders = new javax.swing.JPanel();
    cmdCreateWorkOrder = new javax.swing.JButton();
    cmdEditWorkOrder = new javax.swing.JButton();
    cmdFindWorkOrder = new javax.swing.JButton();
    cmdCompleteWorkOrder = new javax.swing.JButton();
    pnlVehicles = new javax.swing.JPanel();
    cmdCreateVehicle = new javax.swing.JButton();
    cmdEditVehicle = new javax.swing.JButton();
    cmdFindVehicle = new javax.swing.JButton();
    pnlWarranties = new javax.swing.JPanel();
    cmdCreateWarranty = new javax.swing.JButton();
    cmdEditWarranty = new javax.swing.JButton();
    cmdRemoveWarranty = new javax.swing.JButton();
    cmdFindWarranty = new javax.swing.JButton();
    pnlServices = new javax.swing.JPanel();
    cmdCreateService = new javax.swing.JButton();
    cmdEditService = new javax.swing.JButton();
    cmdRemoveService = new javax.swing.JButton();
    pnlWorkOrders5 = new javax.swing.JPanel();
    cmdProfitReport = new javax.swing.JButton();
    cmdTechnicianReport = new javax.swing.JButton();
    cmdHoursWorkedReport = new javax.swing.JButton();
    cmdCustomerReport = new javax.swing.JButton();
    cmdVehicleHistory = new javax.swing.JButton();
    cmdServicesPerformed = new javax.swing.JButton();
    pnlWorkOrders6 = new javax.swing.JPanel();
    cmdCreateUser = new javax.swing.JButton();
    cmdEditUser = new javax.swing.JButton();
    cmdFindUser = new javax.swing.JButton();
    cmdChangePassword = new javax.swing.JButton();
    pnlWorkOrders7 = new javax.swing.JPanel();
    cmdCreateInventory = new javax.swing.JButton();
    cmdEditInventory = new javax.swing.JButton();
    cmdRemoveInventory = new javax.swing.JButton();
    cmdFindInventory = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Top Gear Shop Portal");

    lblWorkOrders.setText("Work Orders");

    lblCustomers.setText("Customers");

    lblVehicles.setText("Vehicles");

    lblInventory.setText("Inventory");

    lblReports.setText("Reports");

    lblUsers.setText("Users");

    lblServiceItems.setText("Services");

    lblWarranty.setText("Warranty");

    pnlCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateCustomer.setText("Create Customer");

    cmdEditCustomer.setText("Edit Customer");

    cmdFindCustomer.setText("Find Customer");

    javax.swing.GroupLayout pnlCustomersLayout = new javax.swing.GroupLayout(pnlCustomers);
    pnlCustomers.setLayout(pnlCustomersLayout);
    pnlCustomersLayout.setHorizontalGroup(
      pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCustomersLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdFindCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdCreateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlCustomersLayout.setVerticalGroup(
      pnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCustomersLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateCustomer)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditCustomer)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cmdFindCustomer)
        .addContainerGap())
    );

    pnlWorkOrders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateWorkOrder.setText("Create Work Order");

    cmdEditWorkOrder.setText("Edit Work Order");

    cmdFindWorkOrder.setText("Find Work Order");

    cmdCompleteWorkOrder.setText("Complete Work Order");

    javax.swing.GroupLayout pnlWorkOrdersLayout = new javax.swing.GroupLayout(pnlWorkOrders);
    pnlWorkOrders.setLayout(pnlWorkOrdersLayout);
    pnlWorkOrdersLayout.setHorizontalGroup(
      pnlWorkOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrdersLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlWorkOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(cmdCompleteWorkOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdCreateWorkOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditWorkOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdFindWorkOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlWorkOrdersLayout.setVerticalGroup(
      pnlWorkOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrdersLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateWorkOrder)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditWorkOrder)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdFindWorkOrder)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdCompleteWorkOrder)
        .addContainerGap(14, Short.MAX_VALUE))
    );

    pnlVehicles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateVehicle.setText("Create Vehicle");

    cmdEditVehicle.setText("Edit Vehicle");

    cmdFindVehicle.setText("Find Vehicle");

    javax.swing.GroupLayout pnlVehiclesLayout = new javax.swing.GroupLayout(pnlVehicles);
    pnlVehicles.setLayout(pnlVehiclesLayout);
    pnlVehiclesLayout.setHorizontalGroup(
      pnlVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlVehiclesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(pnlVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(cmdEditVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cmdFindVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlVehiclesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdCreateVehicle, cmdFindVehicle});

    pnlVehiclesLayout.setVerticalGroup(
      pnlVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlVehiclesLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateVehicle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditVehicle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cmdFindVehicle)
        .addContainerGap())
    );

    pnlWarranties.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateWarranty.setText("Create Warranty");

    cmdEditWarranty.setText("Edit Warranty");

    cmdRemoveWarranty.setText("Remove Warranty");

    cmdFindWarranty.setText("Find Warranty");

    javax.swing.GroupLayout pnlWarrantiesLayout = new javax.swing.GroupLayout(pnlWarranties);
    pnlWarranties.setLayout(pnlWarrantiesLayout);
    pnlWarrantiesLayout.setHorizontalGroup(
      pnlWarrantiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWarrantiesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlWarrantiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(cmdRemoveWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdCreateWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdFindWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlWarrantiesLayout.setVerticalGroup(
      pnlWarrantiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWarrantiesLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateWarranty)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditWarranty)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cmdFindWarranty)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdRemoveWarranty)
        .addContainerGap())
    );

    pnlServices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateService.setText("Create Service");

    cmdEditService.setText("Edit Service");

    cmdRemoveService.setText("Remove Service");

    javax.swing.GroupLayout pnlServicesLayout = new javax.swing.GroupLayout(pnlServices);
    pnlServices.setLayout(pnlServicesLayout);
    pnlServicesLayout.setHorizontalGroup(
      pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlServicesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdRemoveService, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlServicesLayout.setVerticalGroup(
      pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlServicesLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateService)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditService)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cmdRemoveService)
        .addContainerGap())
    );

    pnlWorkOrders5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdProfitReport.setText("Profit");

    cmdTechnicianReport.setText("Technician");

    cmdHoursWorkedReport.setText("Hours Worked");

    cmdCustomerReport.setText("Customer");

    cmdVehicleHistory.setText("Vehicle History");

    cmdServicesPerformed.setText("Services Performed");

    javax.swing.GroupLayout pnlWorkOrders5Layout = new javax.swing.GroupLayout(pnlWorkOrders5);
    pnlWorkOrders5.setLayout(pnlWorkOrders5Layout);
    pnlWorkOrders5Layout.setHorizontalGroup(
      pnlWorkOrders5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrders5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlWorkOrders5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdProfitReport, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmdServicesPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdTechnicianReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdHoursWorkedReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdCustomerReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdVehicleHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlWorkOrders5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdCustomerReport, cmdHoursWorkedReport, cmdProfitReport, cmdServicesPerformed, cmdTechnicianReport, cmdVehicleHistory});

    pnlWorkOrders5Layout.setVerticalGroup(
      pnlWorkOrders5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrders5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdProfitReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdTechnicianReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdHoursWorkedReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdCustomerReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdVehicleHistory)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdServicesPerformed)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlWorkOrders6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateUser.setText("Create User");

    cmdEditUser.setText("Edit User");

    cmdFindUser.setText("Find User");

    cmdChangePassword.setText("Change Password");

    javax.swing.GroupLayout pnlWorkOrders6Layout = new javax.swing.GroupLayout(pnlWorkOrders6);
    pnlWorkOrders6.setLayout(pnlWorkOrders6Layout);
    pnlWorkOrders6Layout.setHorizontalGroup(
      pnlWorkOrders6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrders6Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlWorkOrders6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateUser)
          .addComponent(cmdEditUser)
          .addComponent(cmdFindUser)
          .addComponent(cmdChangePassword))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlWorkOrders6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdChangePassword, cmdCreateUser, cmdEditUser, cmdFindUser});

    pnlWorkOrders6Layout.setVerticalGroup(
      pnlWorkOrders6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrders6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateUser)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditUser)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdFindUser)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cmdChangePassword)
        .addContainerGap())
    );

    pnlWorkOrders7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateInventory.setText("Create Inventory");

    cmdEditInventory.setText("Edit Inventory");

    cmdRemoveInventory.setText("Remove Inventory");

    cmdFindInventory.setText("Find Inventory");

    javax.swing.GroupLayout pnlWorkOrders7Layout = new javax.swing.GroupLayout(pnlWorkOrders7);
    pnlWorkOrders7.setLayout(pnlWorkOrders7Layout);
    pnlWorkOrders7Layout.setHorizontalGroup(
      pnlWorkOrders7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrders7Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlWorkOrders7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdEditInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdCreateInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(pnlWorkOrders7Layout.createSequentialGroup()
            .addComponent(cmdRemoveInventory)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(cmdFindInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlWorkOrders7Layout.setVerticalGroup(
      pnlWorkOrders7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlWorkOrders7Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateInventory)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdEditInventory)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdFindInventory)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cmdRemoveInventory)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(activityView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(pnlWorkOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(lblReports)
                      .addComponent(pnlWorkOrders5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(pnlCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarranty)
                    .addComponent(pnlWarranties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblWorkOrders)
                .addGap(148, 148, 148)
                .addComponent(lblCustomers)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lblInventory)
                .addComponent(pnlWorkOrders7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(lblVehicles))
            .addGap(32, 32, 32)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pnlServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblServiceItems)
              .addComponent(lblUsers)
              .addComponent(pnlWorkOrders6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(7, 7, 7)
        .addComponent(activityView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblWorkOrders)
              .addComponent(lblCustomers))
            .addGap(13, 13, 13)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pnlWorkOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(pnlCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(lblUsers)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlWorkOrders6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(lblWarranty)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlWarranties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(lblInventory)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlWorkOrders7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReports)
                .addGap(12, 12, 12)
                .addComponent(pnlWorkOrders5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lblVehicles)
              .addComponent(lblServiceItems))
            .addGap(13, 13, 13)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(pnlVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(pnlServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TopGearMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TopGearMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TopGearMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TopGearMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TopGearMainUI().setVisible(true);
      }
    });
  }
public void setChangePasswordActionListener(ActionListener al){
    cmdChangePassword.addActionListener(al);
}
public void setCompleteWorkOrderActionListener(ActionListener al){
    cmdCompleteWorkOrder.addActionListener(al);
}
public void setCreateCustomerActionListener(ActionListener al){
    cmdCreateCustomer.addActionListener(al);
}
public void setCreateInventoryActionListener(ActionListener al){
    cmdCreateInventory.addActionListener(al);
}
public void setCreateServiceActionListener(ActionListener al){
    cmdCreateService.addActionListener(al);
}
public void setCreateUserActionListener(ActionListener al){
    cmdCreateUser.addActionListener(al);
}
public void setCreateVehicleActionListener(ActionListener al){
    cmdCreateVehicle.addActionListener(al);
}
public void setCreateWarrantyActionListener(ActionListener al){
    cmdCreateWarranty.addActionListener(al);
}
public void setCreateWorkOrderActionListener(ActionListener al){
    cmdCreateWorkOrder.addActionListener(al);
}
public void setCustomerReportActionListener(ActionListener al){
    cmdCustomerReport.addActionListener(al);
}
public void setEditCustomerActionListener(ActionListener al){
    cmdEditCustomer.addActionListener(al);
}
public void setEditInventoryActionListener(ActionListener al){
    cmdEditInventory.addActionListener(al);
}
public void setEditServiceActionListener(ActionListener al){
    cmdEditService.addActionListener(al);
}
public void setEditUserActionListener(ActionListener al){
    cmdEditUser.addActionListener(al);
}
public void setEditVehicleActionListener(ActionListener al){
    cmdEditVehicle.addActionListener(al);
}
public void setEditWarrantyActionListener(ActionListener al){
    cmdEditWarranty.addActionListener(al);
}
public void setEditWorkOrderActionListener(ActionListener al){
    cmdEditWorkOrder.addActionListener(al);
}
public void setFindCustomerActionListener(ActionListener al){
    cmdFindCustomer.addActionListener(al);
}
public void setFindInventoryActionListener(ActionListener al){
    cmdFindInventory.addActionListener(al);
}
public void setFindUserActionListener(ActionListener al){
    cmdFindUser.addActionListener(al);
}
public void setFindVehicleActionListener(ActionListener al){
    cmdFindVehicle.addActionListener(al);
}
public void setFindWarrantyActionListener(ActionListener al){
    cmdFindWarranty.addActionListener(al);
}
public void setFindWorkOrderActionListener(ActionListener al){
    cmdFindWorkOrder.addActionListener(al);
}
public void setHoursWorkedReportActionListener(ActionListener al){
    cmdHoursWorkedReport.addActionListener(al);
}
public void setProfitReportActionListener(ActionListener al){
    cmdProfitReport.addActionListener(al);
}
public void setRemoveInventoryActionListener(ActionListener al){
    cmdRemoveInventory.addActionListener(al);
}
public void setRemoveServiceActionListener(ActionListener al){
    cmdRemoveService.addActionListener(al);
}
public void setRemoveWarrantyActionListener(ActionListener al){
    cmdRemoveWarranty.addActionListener(al);
}
public void setServicesPerformedActionListener(ActionListener al){
    cmdServicesPerformed.addActionListener(al);
}
public void setTechnicianReportActionListener(ActionListener al){
    cmdTechnicianReport.addActionListener(al);
}
public void setVehicleHistoryActionListener(ActionListener al){
    cmdVehicleHistory.addActionListener(al);
}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private topgearshop.views.ActivityView activityView1;
  private javax.swing.JButton cmdChangePassword;
  private javax.swing.JButton cmdCompleteWorkOrder;
  private javax.swing.JButton cmdCreateCustomer;
  private javax.swing.JButton cmdCreateInventory;
  private javax.swing.JButton cmdCreateService;
  private javax.swing.JButton cmdCreateUser;
  private javax.swing.JButton cmdCreateVehicle;
  private javax.swing.JButton cmdCreateWarranty;
  private javax.swing.JButton cmdCreateWorkOrder;
  private javax.swing.JButton cmdCustomerReport;
  private javax.swing.JButton cmdEditCustomer;
  private javax.swing.JButton cmdEditInventory;
  private javax.swing.JButton cmdEditService;
  private javax.swing.JButton cmdEditUser;
  private javax.swing.JButton cmdEditVehicle;
  private javax.swing.JButton cmdEditWarranty;
  private javax.swing.JButton cmdEditWorkOrder;
  private javax.swing.JButton cmdFindCustomer;
  private javax.swing.JButton cmdFindInventory;
  private javax.swing.JButton cmdFindUser;
  private javax.swing.JButton cmdFindVehicle;
  private javax.swing.JButton cmdFindWarranty;
  private javax.swing.JButton cmdFindWorkOrder;
  private javax.swing.JButton cmdHoursWorkedReport;
  private javax.swing.JButton cmdProfitReport;
  private javax.swing.JButton cmdRemoveInventory;
  private javax.swing.JButton cmdRemoveService;
  private javax.swing.JButton cmdRemoveWarranty;
  private javax.swing.JButton cmdServicesPerformed;
  private javax.swing.JButton cmdTechnicianReport;
  private javax.swing.JButton cmdVehicleHistory;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel lblCustomers;
  private javax.swing.JLabel lblInventory;
  private javax.swing.JLabel lblReports;
  private javax.swing.JLabel lblServiceItems;
  private javax.swing.JLabel lblUsers;
  private javax.swing.JLabel lblVehicles;
  private javax.swing.JLabel lblWarranty;
  private javax.swing.JLabel lblWorkOrders;
  private javax.swing.JPanel pnlCustomers;
  private javax.swing.JPanel pnlServices;
  private javax.swing.JPanel pnlVehicles;
  private javax.swing.JPanel pnlWarranties;
  private javax.swing.JPanel pnlWorkOrders;
  private javax.swing.JPanel pnlWorkOrders5;
  private javax.swing.JPanel pnlWorkOrders6;
  private javax.swing.JPanel pnlWorkOrders7;
  // End of variables declaration//GEN-END:variables
}
