/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package topgearshop.views;

import java.awt.event.ActionListener;
import topgearshop.models.*;

/**
 *
 * @author rmattaway
 */
public class TopGearShopMainUI extends javax.swing.JFrame {

  /**
   * Creates new form TopGearShopMainUI
   */
  public TopGearShopMainUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    viewActivity = new topgearshop.views.ActivityView();
    workOrderUI = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    lblWorkOrders = new javax.swing.JLabel();
    lblCustomers = new javax.swing.JLabel();
    customerUI = new javax.swing.JPanel();
    cmdCreateCustomer = new javax.swing.JButton();
    cmdEditCustomer = new javax.swing.JButton();
    cmdFindCustomer = new javax.swing.JButton();
    customerUI1 = new javax.swing.JPanel();
    cmdCreateInventory = new javax.swing.JButton();
    cmdEditInventory = new javax.swing.JButton();
    cmdFindInventory = new javax.swing.JButton();
    lblInventory = new javax.swing.JLabel();
    lblVehicle = new javax.swing.JLabel();
    customerUI2 = new javax.swing.JPanel();
    cmdCreateVehicle = new javax.swing.JButton();
    cmdEditVehicle = new javax.swing.JButton();
    cmdFindVehicle = new javax.swing.JButton();
    customerUI3 = new javax.swing.JPanel();
    cmdCreateUser = new javax.swing.JButton();
    cmdEditUser = new javax.swing.JButton();
    cmdFindUser = new javax.swing.JButton();
    cmdChangePassword = new javax.swing.JButton();
    lblUser = new javax.swing.JLabel();
    lblReports = new javax.swing.JLabel();
    customerUI4 = new javax.swing.JPanel();
    cmdProfitReport = new javax.swing.JButton();
    cmdTechnicianReport = new javax.swing.JButton();
    cmdHoursWorkedReport = new javax.swing.JButton();
    cmdCustomerReport = new javax.swing.JButton();
    cmdServicesPerformedReport = new javax.swing.JButton();
    cmdVehicleHistoryReport = new javax.swing.JButton();
    lblWarranty = new javax.swing.JLabel();
    customerUI5 = new javax.swing.JPanel();
    cmdCreateWarranty = new javax.swing.JButton();
    cmdEditWarranty = new javax.swing.JButton();
    cmdRemoveWarranty = new javax.swing.JButton();
    lblServices = new javax.swing.JLabel();
    customerUI6 = new javax.swing.JPanel();
    cmdCreateService = new javax.swing.JButton();
    cmdEditService = new javax.swing.JButton();
    cmdRemoveService = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Top Gear Shop");
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Top Gear Shop Management System Portal");

    workOrderUI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jButton1.setText("Create Work Order");

    jButton2.setText("Edit Work Order");

    jButton3.setText("Find Work Order");

    jButton4.setText("Complete Work Order");

    javax.swing.GroupLayout workOrderUILayout = new javax.swing.GroupLayout(workOrderUI);
    workOrderUI.setLayout(workOrderUILayout);
    workOrderUILayout.setHorizontalGroup(
      workOrderUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(workOrderUILayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(workOrderUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    workOrderUILayout.setVerticalGroup(
      workOrderUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(workOrderUILayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1)
        .addGap(18, 18, 18)
        .addComponent(jButton2)
        .addGap(18, 18, 18)
        .addComponent(jButton3)
        .addGap(18, 18, 18)
        .addComponent(jButton4)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lblWorkOrders.setText("Work Orders");

    lblCustomers.setText("Customers");

    customerUI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateCustomer.setText("Create Customer");

    cmdEditCustomer.setText("Edit Customer");

    cmdFindCustomer.setText("Find Customer");

    javax.swing.GroupLayout customerUILayout = new javax.swing.GroupLayout(customerUI);
    customerUI.setLayout(customerUILayout);
    customerUILayout.setHorizontalGroup(
      customerUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUILayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdFindCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUILayout.setVerticalGroup(
      customerUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUILayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateCustomer)
        .addGap(18, 18, 18)
        .addComponent(cmdEditCustomer)
        .addGap(18, 18, 18)
        .addComponent(cmdFindCustomer)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    customerUI1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateInventory.setText("Create Inventory");

    cmdEditInventory.setText("Edit Inventory");

    cmdFindInventory.setText("Find Inventory");

    javax.swing.GroupLayout customerUI1Layout = new javax.swing.GroupLayout(customerUI1);
    customerUI1.setLayout(customerUI1Layout);
    customerUI1Layout.setHorizontalGroup(
      customerUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdFindInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUI1Layout.setVerticalGroup(
      customerUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateInventory)
        .addGap(18, 18, 18)
        .addComponent(cmdEditInventory)
        .addGap(18, 18, 18)
        .addComponent(cmdFindInventory)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lblInventory.setText("Inventory");

    lblVehicle.setText("Vehicle");

    customerUI2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateVehicle.setText("Create Vehicle");

    cmdEditVehicle.setText("Edit Vehicle");

    cmdFindVehicle.setText("Find Vehicle");

    javax.swing.GroupLayout customerUI2Layout = new javax.swing.GroupLayout(customerUI2);
    customerUI2.setLayout(customerUI2Layout);
    customerUI2Layout.setHorizontalGroup(
      customerUI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
          .addComponent(cmdEditVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdFindVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUI2Layout.setVerticalGroup(
      customerUI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateVehicle)
        .addGap(18, 18, 18)
        .addComponent(cmdEditVehicle)
        .addGap(18, 18, 18)
        .addComponent(cmdFindVehicle)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    customerUI3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateUser.setText("Create User");

    cmdEditUser.setText("Edit User");

    cmdFindUser.setText("Find User");

    cmdChangePassword.setText("Change Password");

    javax.swing.GroupLayout customerUI3Layout = new javax.swing.GroupLayout(customerUI3);
    customerUI3.setLayout(customerUI3Layout);
    customerUI3Layout.setHorizontalGroup(
      customerUI3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUI3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdFindUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdChangePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUI3Layout.setVerticalGroup(
      customerUI3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateUser)
        .addGap(18, 18, 18)
        .addComponent(cmdEditUser)
        .addGap(18, 18, 18)
        .addComponent(cmdFindUser)
        .addGap(18, 18, 18)
        .addComponent(cmdChangePassword)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lblUser.setText("User");

    lblReports.setText("Reports");

    customerUI4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdProfitReport.setText("Profit");

    cmdTechnicianReport.setText("Technician");

    cmdHoursWorkedReport.setText("Hours Worked");

    cmdCustomerReport.setText("Customer");

    cmdServicesPerformedReport.setText("Services Performed");

    cmdVehicleHistoryReport.setText("Vehicle History");

    javax.swing.GroupLayout customerUI4Layout = new javax.swing.GroupLayout(customerUI4);
    customerUI4.setLayout(customerUI4Layout);
    customerUI4Layout.setHorizontalGroup(
      customerUI4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUI4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdProfitReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdTechnicianReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdHoursWorkedReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdCustomerReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdServicesPerformedReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdVehicleHistoryReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUI4Layout.setVerticalGroup(
      customerUI4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdProfitReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdTechnicianReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdHoursWorkedReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdCustomerReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdVehicleHistoryReport)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmdServicesPerformedReport)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lblWarranty.setText("Warranty");

    customerUI5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateWarranty.setText("Create Warranty");

    cmdEditWarranty.setText("Edit Warranty");

    cmdRemoveWarranty.setText("Remove Warranty");

    javax.swing.GroupLayout customerUI5Layout = new javax.swing.GroupLayout(customerUI5);
    customerUI5.setLayout(customerUI5Layout);
    customerUI5Layout.setHorizontalGroup(
      customerUI5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUI5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdRemoveWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUI5Layout.setVerticalGroup(
      customerUI5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateWarranty)
        .addGap(18, 18, 18)
        .addComponent(cmdEditWarranty)
        .addGap(18, 18, 18)
        .addComponent(cmdRemoveWarranty)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lblServices.setText("Offered Services");

    customerUI6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    cmdCreateService.setText("Create Service");

    cmdEditService.setText("Edit Service");

    cmdRemoveService.setText("Remove Service");

    javax.swing.GroupLayout customerUI6Layout = new javax.swing.GroupLayout(customerUI6);
    customerUI6.setLayout(customerUI6Layout);
    customerUI6Layout.setHorizontalGroup(
      customerUI6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI6Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(customerUI6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(cmdCreateService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdEditService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cmdRemoveService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    customerUI6Layout.setVerticalGroup(
      customerUI6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(customerUI6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cmdCreateService)
        .addGap(18, 18, 18)
        .addComponent(cmdEditService)
        .addGap(18, 18, 18)
        .addComponent(cmdRemoveService)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(viewActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblWorkOrders)
              .addComponent(workOrderUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblCustomers)
              .addComponent(customerUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblInventory)
              .addComponent(customerUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblUser)
              .addComponent(customerUI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblVehicle)
              .addComponent(customerUI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblReports)
              .addComponent(customerUI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblWarranty)
              .addComponent(customerUI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblServices)
              .addComponent(customerUI6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(viewActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblWorkOrders)
                .addComponent(lblCustomers))
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(workOrderUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
              .addComponent(lblInventory)
              .addGap(18, 18, 18)
              .addComponent(customerUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblUser)
            .addGap(18, 18, 18)
            .addComponent(customerUI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(34, 34, 34)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblReports)
            .addGap(18, 18, 18)
            .addComponent(customerUI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblServices)
                .addGap(18, 18, 18)
                .addComponent(customerUI6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(lblVehicle)
                  .addGap(18, 18, 18)
                  .addComponent(customerUI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(lblWarranty)
                  .addGap(18, 18, 18)
                  .addComponent(customerUI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 0, Short.MAX_VALUE))))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TopGearShopMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TopGearShopMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TopGearShopMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TopGearShopMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TopGearShopMainUI().setVisible(true);
      }
    });
  }
  public void setChangePasswordAction(ActionListener al)
  {
    cmdChangePassword.addActionListener(al);
  }
  public void setCreateCustomerAction(ActionListener al)
  {
    cmdCreateCustomer.addActionListener(al);
  }
  public void setCreateInventoryAction(ActionListener al)
  {
    cmdCreateInventory.addActionListener(al);
  }
  public void setCreateServiceAction(ActionListener al)
  {
    cmdCreateService.addActionListener(al);
  }
  public void setCreateUserAction(ActionListener al)
  {
    cmdCreateUser.addActionListener(al);
  }
  public void setCreateVehicleAction(ActionListener al)
  {
    cmdCreateVehicle.addActionListener(al);
  }
  public void setCreateWarrantyAction(ActionListener al)
  {
    cmdCreateWarranty.addActionListener(al);
  }
  public void setCustomerReportAction(ActionListener al)
  {
    cmdCustomerReport.addActionListener(al);
  }
  public void setEditCustomerAction(ActionListener al)
  {
    cmdEditCustomer.addActionListener(al);
  }
  public void setEditInventoryAction(ActionListener al)
  {
    cmdEditInventory.addActionListener(al);
  }
  public void setEditServiceAction(ActionListener al)
  {
    cmdEditService.addActionListener(al);
  }
  public void setEditUserAction(ActionListener al)
  {
    cmdEditUser.addActionListener(al);
  }
  public void setEditVehicleAction(ActionListener al)
  {
    cmdEditVehicle.addActionListener(al);
  }
  public void setEditWarrantyAction(ActionListener al)
  {
    cmdEditWarranty.addActionListener(al);
  }
  public void setFindCustomerAction(ActionListener al)
  {
    cmdFindCustomer.addActionListener(al);
  }
  public void setFindInventoryAction(ActionListener al)
  {
    cmdFindInventory.addActionListener(al);
  }
  public void setFinduserAction (ActionListener al)
  {
    cmdFindUser.addActionListener(al);
  }
  public void setFindVehicleAction (ActionListener al)
  {
    cmdFindVehicle.addActionListener(al);
  }
  public void setHoursWorkedReportAction (ActionListener al)
  {
    cmdHoursWorkedReport.addActionListener(al);
  }
  public void setProfitReportAction (ActionListener al)
  {
    cmdProfitReport.addActionListener(al);
  }
  public void setRemoveServiceAction (ActionListener al)
  {
    cmdRemoveService.addActionListener(al);
  }
  public void setRemoveWarrantyAction (ActionListener al)
  {
    cmdRemoveWarranty.addActionListener(al);
  }
  public void setServicesPerformedReportAction (ActionListener al)
  {
    cmdServicesPerformedReport.addActionListener(al);
  }
  public void setTechnicianReportAction (ActionListener al)
  {
    cmdTechnicianReport.addActionListener(al);
  }
  public void setVehicleHistoryReportAction (ActionListener al)
  {
    cmdVehicleHistoryReport.addActionListener(al);
  }
 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cmdChangePassword;
  private javax.swing.JButton cmdCreateCustomer;
  private javax.swing.JButton cmdCreateInventory;
  private javax.swing.JButton cmdCreateService;
  private javax.swing.JButton cmdCreateUser;
  private javax.swing.JButton cmdCreateVehicle;
  private javax.swing.JButton cmdCreateWarranty;
  private javax.swing.JButton cmdCustomerReport;
  private javax.swing.JButton cmdEditCustomer;
  private javax.swing.JButton cmdEditInventory;
  private javax.swing.JButton cmdEditService;
  private javax.swing.JButton cmdEditUser;
  private javax.swing.JButton cmdEditVehicle;
  private javax.swing.JButton cmdEditWarranty;
  private javax.swing.JButton cmdFindCustomer;
  private javax.swing.JButton cmdFindInventory;
  private javax.swing.JButton cmdFindUser;
  private javax.swing.JButton cmdFindVehicle;
  private javax.swing.JButton cmdHoursWorkedReport;
  private javax.swing.JButton cmdProfitReport;
  private javax.swing.JButton cmdRemoveService;
  private javax.swing.JButton cmdRemoveWarranty;
  private javax.swing.JButton cmdServicesPerformedReport;
  private javax.swing.JButton cmdTechnicianReport;
  private javax.swing.JButton cmdVehicleHistoryReport;
  private javax.swing.JPanel customerUI;
  private javax.swing.JPanel customerUI1;
  private javax.swing.JPanel customerUI2;
  private javax.swing.JPanel customerUI3;
  private javax.swing.JPanel customerUI4;
  private javax.swing.JPanel customerUI5;
  private javax.swing.JPanel customerUI6;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel lblCustomers;
  private javax.swing.JLabel lblInventory;
  private javax.swing.JLabel lblReports;
  private javax.swing.JLabel lblServices;
  private javax.swing.JLabel lblUser;
  private javax.swing.JLabel lblVehicle;
  private javax.swing.JLabel lblWarranty;
  private javax.swing.JLabel lblWorkOrders;
  public topgearshop.views.ActivityView viewActivity;
  private javax.swing.JPanel workOrderUI;
  // End of variables declaration//GEN-END:variables
}
