//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : ActivityTypeModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class ActivityTypeModel {
	/** */
	private Integer activityTypeID;
	
	/** */
	private String activityName;
	
	/** */
	private Integer roleID;
	
	/** 
   @return activityTypeID 
   */
	public Integer getActivityTypeID() {
    return this.activityTypeID;
	}
	
	/** 
   @param activityTypeID
   */
	public void setActivityTypeID(Integer activityTypeID) {
    this.activityTypeID=activityTypeID;
	}
	
	/** 
   @return activityName
   */
	public String getActivityName() {
    return this.activityName;
	}
	
	/** 
   @param activityName
   */
	public void setActivityName(String activityName) {
    this.activityName = activityName;
	}
	
	/** 
   @return roleID
   */
	public Integer getRoleID() {
    return this.roleID;
	}
	
	/** 
   @param roleID
   */
	public void setRoleID(Integer roleID) {
    this.roleID = roleID;
	}
}
