//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : CredentialsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class CredentialsModel {
	/** */
	private String employeeID;
	
	/** */
	private String userName;
	
	/** */
	private String password;
	
	/** */
	private String salt;
	
	/** */
	public String getEmployeeID() {
	 return this.employeeID;
	}
	
	/** */
	public void setEmployeeID(String employeeID) {
    this.employeeID = employeeID;
	}
	
	/** */
	public String getUserName() {
    return this.userName;
	}
	
	/** */
	public void setUserName(String userName) {
    this.userName = userName;
	}
	
	/** */
	public String getPassword() {
    return this.password;
	}
	
	/** */
	public void setPassword(String password) {
    this.password = password;
	}
	
	/** */
	public String getSalt() {
    return this.salt;
	}
	
	/** */
	public void setSalt(String salt) {
    this.salt = salt;
	}
}
