//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : CustomerModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class CustomerModel {
	/** */
	private Integer customerID;
	
	/** */
	private String phoneNumber;
	
	/** */
	private String firstName;
	
	/** */
	private String lastName;
	
	/** */
	private String emailAddress;
	
	/** */
	private String streetAddress;
	
	/** */
	private String city;
	
	/** */
	private String state;
	
	/** */
	private String zipCode;
	
	/** */
	public Integer getCustomerID() {
    return this.customerID;
	}
	
	/** */
	public void setCustomerID(Integer customerID) {
    this.customerID = customerID;
	}
	
	/** */
	public String getPhoneNumber() {
    return this.phoneNumber;
	}
	
	/** */
	public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
	}
	
	/** */
	public String getFirstName() {
      return this.firstName;
	}
	
	/** */
	public void setFirstName(String firstName) {
    this.firstName = firstName;	
	}
	
	/** */
	public String getLastName() {
    return this.lastName;
	}
	
	/** */
	public void setLastName(String lastName) {
    this.lastName = lastName;
	}
	
	/** */
	public String getEmailAddress() {
    return this.emailAddress;
	}
	
	/** */
	public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
	}
	
	/** */
	public String getStreetAddress() {
    return this.streetAddress;
	}
	
	/** */
	public void setStreetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
	}
	
	/** */
	public String getCity() {
    return this.city;
	}
	
	/** */
	public void setCitty(String city) {
    this.city = city;
	}
	
	/** */
	public String getState() {
    return this.state;
	}
	
	/** */
	public void setState(String state) {
    this.state = state;
	}
	
	/** */
	public String getZipCode() {
    return this.zipCode;
	}
	
	/** */
	public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
	}
}
