//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : CustomerVehicleModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class CustomerVehicleModel {
	/** */
	private String customerVehicleID;
	
	/** */
	private Integer customerID;
	
	/** */
	private String vehicleIDNumber;
	
	/** */
	public String getCustomerVehicleID() {
    return this.customerVehicleID;
	}
	
	/** */
	public void setCustomerVehicleID(String customerVehicleID) {
    this.customerVehicleID  = customerVehicleID;
	}
	
	/** */
	public Integer getCustomerID() {
    return this.customerID;
	}
	
	/** */
	public void setCustomerID(Integer customerID) {
    this.customerID = customerID;
	}
	
	/** */
	public String getVehicleIDNumber() {
    return this.vehicleIDNumber;
	}
	
	/** */
	public void setVehicleIDNumber(String vehicleIDNumber) {
    this.vehicleIDNumber = vehicleIDNumber;
	}
}
