//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : DiscountsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class DiscountsModel {
	/** */
	private Integer serviceItemID;
	
	/** */
	private Double discount;
	
	/** */
	public Integer getServiceItemID() {
    return this.serviceItemID;
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
    this.serviceItemID = serviceItemID;
	}
	
	/** */
	public Double getDiscount() {
    return this.discount;
	}
	
	/** */
	public void setDiscount(Double discount) {
    this.discount = discount;
	}
}
