//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : EmployeeModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class EmployeeModel {
	/** */
	private String employeeID;
	
	/** */
	private String firstName;
	
	/** */
	private String middleName;
	
	/** */
	private String lastName;
	
	/** */
	private Date dateOfBirth;
	
	/** */
	private String driversLicenseNumber;
	
	/** */
	private Integer employeeTypeID;
	
	/** */
	public String getEmployeeID() {
	
	}
	
	/** */
	public void setEmployeeID(String employeeID) {
	
	}
	
	/** */
	public String getFirstName() {
	
	}
	
	/** */
	public void setFirstName(String firstName) {
	
	}
	
	/** */
	public String getMiddleName() {
	
	}
	
	/** */
	public void setMiddleName(String middleName) {
	
	}
	
	/** */
	public String getLastName() {
	
	}
	
	/** */
	public void setLastName(String lastName) {
	
	}
	
	/** */
	public Date getDateOfBirth() {
	
	}
	
	/** */
	public void setDateOfBirth(Date dateOfBirth) {
	
	}
	
	/** */
	public String getDriversLicenseNumber() {
	
	}
	
	/** */
	public void setDriversLicenseNumber(String driversLicenseNumber) {
	
	}
	
	/** */
	public Integer getEmployeeTypeID() {
	
	}
	
	/** */
	public void setEmployeeTypeID(Integer employeeTypeID) {
	
	}
}
