//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : EmployeeTypeModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class EmployeeTypeModel {
	/** */
	private Integer employeeTypeId;
	
	/** */
	private String employeeType;
	
	/** */
	public Integer getEmployeeTypeID() {
	
	}
	
	/** */
	public void setEmployeeTypeID(Integer employeeTypeID) {
	
	}
	
	/** */
	public String getEmployeeType() {
	
	}
	
	/** */
	public void setEmployeeType(String employeeType) {
	
	}
}
