//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : EmployeeRoleModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class EmployeeRoleModel {
	/** */
	private String employeeID;
	
	/** */
	private Integer roleID;
	
	/** */
	public String getEmployeeID() {
    return this.employeeID;
	}
	
	/** */
	public void setEmployeeID(String employeeID) {
    this.employeeID = employeeID;
	}
	
	/** */
	public Integer getRoleID() {
    return this.roleID;
	}
	
	/** */
	public void setRoleID(Integer roleID) {
    this.roleID = roleID;
	}
}
