//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : InventoryItemModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class InventoryItemModel {
	/** */
	private Integer inventoryItemID;
	
	/** */
	private String itemName;
	
	/** */
	private Double itemCost;
	
	/** */
	private Double sellingPrice;
	
	/** */
	private String locationInShop;
	
	/** */
	private Integer quantityOnHand;
	
	/** */
	private Integer reorderLevel;
	
	/** */
	private Double grossProfit;
	
	/** */
	public Integer getInventoryItemID() {
	
	}
	
	/** */
	public void setInventoryItemID(Integer inventoryItemID) {
	
	}
	
	/** */
	public String getItemName() {
	
	}
	
	/** */
	public void setItemName(String itemName) {
	
	}
	
	/** */
	public Double getItemCost() {
	
	}
	
	/** */
	public void setItemCost(Double itemCost) {
	
	}
	
	/** */
	public Double getSellingPrice() {
	
	}
	
	/** */
	public void setSellingPrice(Double sellingPrice) {
	
	}
	
	/** */
	public String getLocationInShop() {
	
	}
	
	/** */
	public void setLocationInShop(String locationInShop) {
	
	}
	
	/** */
	public Integer getQuantityOnHand() {
	
	}
	
	/** */
	public void setQuantityOnHand(Integer quantittyOnHand) {
	
	}
	
	/** */
	public Integer getReorderLevel() {
	
	}
	
	/** */
	public void setReorderLevel(Integer reorderLevel) {
	
	}
	
	/** */
	public Double getGrossProfit() {
	
	}
	
	/** */
	public void setGrossProfit(Double grossProfit) {
	
	}
}
