//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : MaterialsListModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class MaterialsListModel {
	/** */
	private Integer materialListID;
	
	/** */
	private Integer serviceItemID;
	
	/** */
	private Integer inventoryItemID;
	
	/** */
	private Integer partID;
	
	/** */
	public Integer getMaterialsListID() {
    return this.materialListID;
	}
	
	/** */
	public void setMaterialsListID(Integer materialListID) {
    this.materialListID = materialListID;
	}
	
	/** */
	public Integer getServiceItemID() {
    return this.serviceItemID;
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
    this.serviceItemID = serviceItemID;
	}
	
	/** */
	public Integer getInventoryItemID() {
    return this.inventoryItemID;
	}
	
	/** */
	public void setInventoryItemID(Integer inventoryItemID) {
    this.inventoryItemID = inventoryItemID;
	}
	
	/** */
	public Integer getPartID() {
    return this.partID;
	}
	
	/** */
	public void setPartID(Integer partID) {
    this.partID = partID;
	}
}
