//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : MaterialsListModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class MaterialsListModel {
	/** */
	private Integer materialListID;
	
	/** */
	private Integer serviceItemID;
	
	/** */
	private Integer inventoryItemID;
	
	/** */
	private Integer partID;
	
	/** */
	public Integer getMaterialsListID() {
	
	}
	
	/** */
	public void setMaterialsListID(Integer materialsListID) {
	
	}
	
	/** */
	public Integer getServiceItemID() {
	
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
	
	}
	
	/** */
	public Integer getInventoryItemID() {
	
	}
	
	/** */
	public void setInventoryItemID(Integer inventoryItemID) {
	
	}
	
	/** */
	public Integer getPartID() {
	
	}
	
	/** */
	public void setPartID(Integer partID) {
	
	}
}
