//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : PartsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class PartsModel {
	/** */
	private Integer partID;
	
	/** */
	private String partName;
	
	/** */
	private Double partCost;
	
	/** */
	private Double sellingPrice;
	
	/** */
	public Integer getPartID() {
    return this.partID;
	}
	
	/** */
	public void setPartID(Integer partID) {
    this.partID = partID;
	}
	
	/** */
	public String getPartName() {
    return this.partName;
	}
	
	/** */
	public void setPartName(String partName) {
    this.partName = partName;
	}
	
	/** */
	public Double getPartCost() {
    return this.partCost;
	}
	
	/** */
	public void setPartCost(Double partCost) {
    this.partCost = partCost;
	}
	
	/** */
	public Double getSellingPrice() {
    return this.sellingPrice;
	}
	
	/** */
	public void setSellingPrice(Double sellingPrice) {
    this.sellingPrice = sellingPrice;
	}
}
