//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : PartsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class PartsModel {
	/** */
	private Integer partID;
	
	/** */
	private String partName;
	
	/** */
	private Double partCost;
	
	/** */
	private Double sellingPrice;
	
	/** */
	public Integer getPartID() {
	
	}
	
	/** */
	public void setPartID(Integer partID) {
	
	}
	
	/** */
	public String getPartName() {
	
	}
	
	/** */
	public void setPartName(String partName) {
	
	}
	
	/** */
	public Double getPartCost() {
	
	}
	
	/** */
	public void setPartCost(Double partCost) {
	
	}
	
	/** */
	public Double getSellingPrice() {
	
	}
	
	/** */
	public void setSellingPrice(Double sellingPrice) {
	
	}
}
