//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : PaymentsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class PaymentsModel {
	/** */
	private Integer paymentID;
	
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer paymentTypeID;
	
	/** */
	private Double paymentAmount;
	
	/** */
	private String approvalCode;
	
	/** */
	public Integer getPaymentID() {
    return this.paymentID;
	}
	
	/** */
	public void setPaymentID(Integer paymentID) {
    this.paymentID = paymentID;
	}
	
	/** */
	public Integer getWorkOrderID() {
    return this.workOrderID;
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
    this.workOrderID = workOrderID;
	}
	
	/** */
	public Integer getPaymentTypeID() {
    return this.paymentTypeID;
	}
	
	/** */
	public void setPaymentTypeID(Integer paymentTypeID) {
    this.paymentTypeID = paymentTypeID;
	}
	
	/** */
	public Double getPaymentAmount() {
    return this.paymentAmount;
	}
	
	/** */
	public void setPaymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
	}
	
	/** */
	public String getApprovalCode() {
    return this.approvalCode;
	}
	
	/** */
	public void setApprovalCode(String approvalCode) {
    this.approvalCode = approvalCode;
	}
}
