//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : PaymentsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class PaymentsModel {
	/** */
	private Integer paymentID;
	
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer paymentTypeID;
	
	/** */
	private Double paymentAmount;
	
	/** */
	private String approvalCode;
	
	/** */
	public Integer getPaymentID() {
	
	}
	
	/** */
	public void setPaymentID(Integer paymentID) {
	
	}
	
	/** */
	public Integer getWorkOrderID() {
	
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
	
	}
	
	/** */
	public Integer getPaymentTypeID() {
	
	}
	
	/** */
	public void setPaymentTypeID(Integer paymentTypeID) {
	
	}
	
	/** */
	public Double getPaymentAmount() {
	
	}
	
	/** */
	public void setPaymentAmount(Double paymentAmount) {
	
	}
	
	/** */
	public String getApprovalCode() {
	
	}
	
	/** */
	public void setApprovalCode(String approvalCode) {
	
	}
}
