//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : PaymentTypesModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class PaymentTypesModel {
	/** */
	private Integer paymentTypeID;
	
	/** */
	private String paymentType;
	
	/** */
	public Integer getPaymentTypeID() {
	
	}
	
	/** */
	public void setPaymentTypeID(Integer paymentTypeID) {
	
	}
	
	/** */
	public String getPaymentType() {
	
	}
	
	/** */
	public void setPaymentType(String paymentType) {
	
	}
}
