//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : RequiredFeesModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class RequiredFeesModel {
	/** */
	private Integer requiredFeeID;
	
	/** */
	private Integer serviceItemID;
	
	/** */
	private Double feeAmount;
	
	/** */
	private Boolean stateRequired;
	
	/** */
	private Boolean localMunicipalityRequired;
	
	/** */
	public Integer getRequiredFeeID() {
	
	}
	
	/** */
	public void setRequiredFeeID(Integer requiredFeeID) {
	
	}
	
	/** */
	public Integer getServiceItemID() {
	
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
	
	}
	
	/** */
	public Double getFeeAmount() {
	
	}
	
	/** */
	public void setFeeAmount(Double feeAmount) {
	
	}
	
	/** */
	public Boolean getStateRequired() {
	
	}
	
	/** */
	public void setStateRequired(Boolean stateRequired) {
	
	}
	
	/** */
	public Boolean getLocalMunicipalityRequired() {
	
	}
	
	/** */
	public void setLocalMunicipalityRequired(Boolean localMunicipalityRequired) {
	
	}
}
