//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : ServiceItemModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class ServiceItemModel {
	/** */
	private Integer serviceItemID;
	
	/** */
	private String serviceItemName;
	
	/** */
	private Double serviceItemCost;
	
	/** */
	private Integer timeRequiredToComplete;
	
	/** */
	private Integer materialListID;
	
	/** */
	private Integer taxRateID;
	
	/** */
	public Integer getServiceItemID() {
	
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
	
	}
	
	/** */
	public String getServiceItemName() {
	
	}
	
	/** */
	public void setServiceItemName(String serviceItemName) {
	
	}
	
	/** */
	public Double getServiceItemCost() {
	
	}
	
	/** */
	public void setServiceItemCost(Double serviceItemCost) {
	
	}
	
	/** */
	public Integer getTimeRequiredToComplete() {
	
	}
	
	/** */
	public void setTimeRequiredToComplete(INteger timeRequiredToComplete) {
	
	}
}
