//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : ServiceItemModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class ServiceItemModel {
	/** */
	private Integer serviceItemID;
	
	/** */
	private String serviceItemName;
	
	/** */
	private Double serviceItemCost;
	
	/** */
	private Integer timeRequiredToComplete;
	
	/** */
	private Integer materialListID;
	
	/** */
	private Integer taxRateID;
	
	/** */
	public Integer getServiceItemID() {
    return this.serviceItemID;
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
    this.serviceItemID = serviceItemID;
	}
	
	/** */
	public String getServiceItemName() {
    return this.serviceItemName;
	}
	
	/** */
	public void setServiceItemName(String serviceItemName) {
    this.serviceItemName = serviceItemName;
	}
	
	/** */
	public Double getServiceItemCost() {
    return this.serviceItemCost;
	}
	
	/** */
	public void setServiceItemCost(Double serviceItemCost) {
    this.serviceItemCost = serviceItemCost;
	}
	
	/** */
	public Integer getTimeRequiredToComplete() {
    return this.timeRequiredToComplete;
	}
	
	/** */
	public void setTimeRequiredToComplete(Integer timeRequiredToComplete) {
    this.timeRequiredToComplete = timeRequiredToComplete;
	}
}
