//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : TaxRateModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class TaxRateModel {
	/** */
	private Integer taxRateID;
	
	/** */
	private Double taxRate;
	
	/** */
	private String governingRequirer;
	
	/** */
	public Integer getTaxRateID() {
    return this.taxRateID;
	}
	
	/** */
	public void setTaxRateID(Integer taxRateID) {
    this.taxRateID = taxRateID;
	}
	
	/** */
	public Double getTaxRate() {
    return this.taxRate;
	}
	
	/** */
	public void setTaxRate(Double taxRate) {
    this.taxRate = taxRate;
	}
	
	/** */
	public String getGoverningRequirer() {
    return this.governingRequirer;
	}
	
	/** */
	public void setGoverningRequirer(String governingRequirer) {
    this.governingRequirer = governingRequirer;
	}
}
