//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : UserRolesModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class UserRolesModel {
	/** */
	private Integer roleID;
	
	/** */
	private String roleName;
	
	/** */
	public Integer getRoleID() {
    return this.roleID;
	}
	
	/** */
	public void setRoleID(Integer roleID) {
    this.roleID = roleID;
	}
	
	/** */
	public String getRoleName() {
    return this.roleName;
	}
	
	/** */
	public void setRoleName(String roleName) {
    this.roleName = roleName;
	}
}
