//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : UserActivityModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class UserActivityModel {
	/** */
	private String employeeID;
	
	/** */
	private Integer activityTypeID;
	
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer workOrderDetailID;
	
	/** */
	private Date dateTimeOfActivity;
	
	/** */
	public String getEmployeeID() {
	
	}
	
	/** */
	public void setEmployeeID(String employeeID) {
	
	}
	
	/** */
	public Integer getActivityTypeID() {
	
	}
	
	/** */
	public void setActivityTypeID(Integer activityTypeID) {
	
	}
	
	/** */
	public Integer getWorkOrderID() {
	
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
	
	}
	
	/** */
	public Integer getWorkOrderDetailID() {
	
	}
	
	/** */
	public void setWorkOrderDetailID(Integer workOrderDetailID) {
	
	}
	
	/** */
	public Date getDateTimeOfActivity() {
	
	}
	
	/** */
	public void setDateTimeOfActivity(Date dateTimeOfActivity) {
	
	}
}
