//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : UserActivityModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;

import java.util.Date;


/** */
public class UserActivityModel {
	/** */
	private String employeeID;
	
	/** */
	private Integer activityTypeID;
	
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer workOrderDetailID;
	
	/** */
	private Date dateTimeOfActivity;
	
	/** */
	public String getEmployeeID() {
    return this.employeeID;
	}
	
	/** */
	public void setEmployeeID(String employeeID) {
    this.employeeID = employeeID;
	}
	
	/** */
	public Integer getActivityTypeID() {
    return this.activityTypeID;
	}
	
	/** */
	public void setActivityTypeID(Integer activityTypeID) {
    this.activityTypeID = activityTypeID;
	}
	
	/** */
	public Integer getWorkOrderID() {
    return this.workOrderID;
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
    this.workOrderID = workOrderID;
	}
	
	/** */
	public Integer getWorkOrderDetailID() {
    return this.workOrderDetailID;
	}
	
	/** */
	public void setWorkOrderDetailID(Integer workOrderDetailID) {
    this.workOrderDetailID = workOrderDetailID;
	}
	
	/** */
	public Date getDateTimeOfActivity() {
    return this.dateTimeOfActivity;
	}
	
	/** */
	public void setDateTimeOfActivity(Date dateTimeOfActivity) {
    this.dateTimeOfActivity = dateTimeOfActivity;
	}
}
