//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : VehicleModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class VehicleModel {
	/** */
	private String vehicleIDNumber;
	
	/** */
	private String year;
	
	/** */
	private String make;
	
	/** */
	private String model;
	
	/** */
	private String color;
	
	/** */
	private Integer mileage;
	
	/** */
	public String getVehicleIDNumber() {
    return this.vehicleIDNumber;
	}
	
	/** */
	public void setVehicleIDNumber(String vehicleIDNumber) {
    this.vehicleIDNumber = vehicleIDNumber;
	}
	
	/** */
	public String getYear() {
    return this.year;
	}
	
	/** */
	public void setYear(String year) {
    this.year = year;
	}
	
	/** */
	public String getMake() {
    return this.make;
	}
	
	/** */
	public void setMake(String make) {
    this.make = make;
	}
	
	/** */
	public String getModel() {
    return this.model;
	}
	
	/** */
	public void setModel(String model) {
    this.model = model;
	}
	
	/** */
	public String getColor() {
    return this.color;
	}
	
	/** */
	public void setColor(String color) {
    this.color = color;
	}
	
	/** */
	public Integer getMileage() {
    return this.mileage;
	}
	
	/** */
	public void setMileage(Integer mileage) {
    this.mileage = mileage;
	}
}
