//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : VehicleModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class VehicleModel {
	/** */
	private String vehicleIDNumber;
	
	/** */
	private String year;
	
	/** */
	private String make;
	
	/** */
	private String model;
	
	/** */
	private String color;
	
	/** */
	private Integer mileage;
	
	/** */
	public String getVehicleIDNumber() {
	
	}
	
	/** */
	public void setVehicleIDNumber(String vehicleIDNumber) {
	
	}
	
	/** */
	public String getYear() {
	
	}
	
	/** */
	public void setYear(String year) {
	
	}
	
	/** */
	public String getMake() {
	
	}
	
	/** */
	public void setMake(String make) {
	
	}
	
	/** */
	public String getModel() {
	
	}
	
	/** */
	public void setModel(String model) {
	
	}
	
	/** */
	public String getColor() {
	
	}
	
	/** */
	public void setColor(String color) {
	
	}
	
	/** */
	public Integer getMilelage() {
	
	}
	
	/** */
	public void setMileage(Integer mileage) {
	
	}
}
