//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : WarrantyModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class WarrantyModel {
	/** */
	private Integer warrantyID;
	
	/** */
	private String warranty;
	
	/** */
	public Integer getWarrantyID() {
    return this.warrantyID;
	}
	
	/** */
	public void setWarrantyID(Integer warrantyID) {
    this.warrantyID = warrantyID;
	}
	
	/** */
	public String getWarranty() {
    return this.warranty;
	}
	
	/** */
	public void setWarranty(String warranty) {
    this.warranty = warranty;
	}
}
