//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : WorkOrderDetailsModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class WorkOrderDetailsModel {
	/** */
	private Integer workOrderDetailID;
	
	/** */
	private Integer workOrderID;
	
	/** */
	private String employeeID;
	
	/** */
	private Integer serviceItemID;
	
	/** */
	private Date startTime;
	
	/** */
	private Date endTime;
	
	/** */
	private String notes;
	
	/** */
	private Double materialsCost;
	
	/** */
	private Double workOrderDetailCost;
	
	/** */
	public Integer getWorkOrderDetailID() {
	
	}
	
	/** */
	public void setWorkOrderDetailID(Integer workOrderDetailID) {
	
	}
	
	/** */
	public Integer getWorkOrderID() {
	
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
	
	}
	
	/** */
	public String getEmployeeID() {
	
	}
	
	/** */
	public void setEmployeeID(String employeeID) {
	
	}
	
	/** */
	public Integer getServiceItemID() {
	
	}
	
	/** */
	public void setServiceItemID(Integer serviceItemID) {
	
	}
	
	/** */
	public Date getStartTime() {
	
	}
	
	/** */
	public void setStartTime(Date startTime) {
	
	}
	
	/** */
	public Date getEndTime() {
	
	}
	
	/** */
	public void setEndTime(Date endTime) {
	
	}
	
	/** */
	public String getNotes() {
	
	}
	
	/** */
	public void setNotes(String notes) {
	
	}
	
	/** */
	public Double getMaterialsCost() {
	
	}
	
	/** */
	public void setMaterialsCost(Double materialsCost) {
	
	}
	
	/** */
	public Double getWorkOrderDetailCost() {
	
	}
	
	/** */
	public void setWorkOrderDetailCost(Double workOrderDetailCost) {
	
	}
}
