//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : WorkOrdersModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;

import java.util.Date;


/** */
public class WorkOrdersModel {
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer customerID;
	
	/** */
	private String vehicleIDNumber;
	
	/** */
	private Date dateWorkCompleted;
	
	/** */
	public Integer getWorkOrderID() {
    return this.workOrderID;
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
    this.workOrderID = workOrderID;
	}
	
	/** */
	public Integer getCustomerID() {
    return this.customerID;
	}
	
	/** */
	public void setCustomerID(Integer customerID) {
    this.customerID = customerID;
	}
	
	/** */
	public String getVehicleIDNumber() {
    return this.vehicleIDNumber;
	}
	
	/** */
	public void setVehicleIDNumber(String vehicleIDNumber) {
    this.vehicleIDNumber = vehicleIDNumber;
	}
  	
	/** */
	public Date getDateWorkCompleted() {
    return this.dateWorkCompleted;
	}
	
	/** */
	public void setDateWorkCompleted(Date dateWorkCompleted) {
    this.dateWorkCompleted = dateWorkCompleted;
	}
}
