//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : WorkOrderItemWarrantyModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class WorkOrderItemWarrantyModel {
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer workOrderDetailID;
	
	/** */
	private Integer warrantyID;
	
	/** */
	private Date dateWarrantyBegins;
	
	/** */
	private Date dateWarrantyEnds;
	
	/** */
	public Integer getWorkOrderID() {
	
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
	
	}
	
	/** */
	public Integer getWorkOrderDetailID() {
	
	}
	
	/** */
	public void setWorkOrderDetailID(Integer workOrderDetailID) {
	
	}
	
	/** */
	public Integer getWarrantyID() {
	
	}
	
	/** */
	public void setWarrantyID(Integer warrantyID) {
	
	}
	
	/** */
	public Date getDateWarrantyBegins() {
	
	}
	
	/** */
	public void setDateWarrantyBegins(Date dateWarrantyBegins) {
	
	}
	
	/** */
	public Date getDateWarrantyEnds() {
	
	}
	
	/** */
	public void setDateWarrantyEnds(Date dateWarrantyEnds) {
	
	}
}
