//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopGear UML ER
//  @ File Name : WorkOrdersModel.java
//  @ Date : 3/18/2014
//  @ Author : 
//
//



package topgearshop.models;


/** */
public class WorkOrdersModel {
	/** */
	private Integer workOrderID;
	
	/** */
	private Integer customerID;
	
	/** */
	private String vehicleIDNumber;
	
	/** */
	private Date dateWorkCompleted;
	
	/** */
	public Integer getWorkOrderID() {
	
	}
	
	/** */
	public void setWorkOrderID(Integer workOrderID) {
	
	}
	
	/** */
	public Integer getCustomerID() {
	
	}
	
	/** */
	public void setCustomerID(Integer customerID) {
	
	}
	
	/** */
	public String getVehicleIDNumber() {
	
	}
	
	/** */
	public void setVehicleIDNumber(String vehicleIDNumber) {
	
	}
}
